plugins {
    id 'java'
    id 'fabric-loom' version '1.1.+'
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
}

jar {
    manifest {
        attributes([
                'FMLModType': 'GAMELIBRARY'
        ])
    }
    rename 'dummy_fabric.mod.json', 'fabric.mod.json'
    inputs.property "version", project.version

    filesMatching('*.mod.json') {
        expand('type': 'regutils-common', 'version': project.version)
    }
}
