plugins {
    id 'java'
    id 'net.neoforged.moddev'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

neoForge {
    neoFormVersion = "${neoform_version}"
}

jar {
    manifest {
        attributes([
                'FMLModType': 'GAMELIBRARY'
        ])
    }
    rename 'dummy_fabric.mod.json', 'fabric.mod.json'
    inputs.property "version", project.version

    filesMatching('*.mod.json') {
        expand('type': 'regutils-common', 'version': project.version)
    }
}
