plugins {
    id 'idea'
    id 'maven-publish'
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.123'
}

neoForge {
    version = "${neoforge_version}"
}

java {
    withJavadocJar()
    withSourcesJar()
}

jar {
    manifest {
        attributes([
                'FMLModType': 'GAMELIBRARY'
        ])
    }
}

dependencies {
    compileOnly project(":Common")
    compileOnly 'com.google.auto.service:auto-service:1.0.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.0.1'
}
