plugins {
    id 'idea'
    id 'maven-publish'
    id 'java-library'
    id 'net.neoforged.moddev' version '0.1.87'
}

neoForge {
    version = "${neoforge_version}"
}

java {
    withJavadocJar()
    withSourcesJar()
}

jar {
    manifest {
        attributes([
                'FMLModType': 'GAMELIBRARY'
        ])
    }
}

dependencies {
    compileOnly project(":Common")
    compileOnly 'com.google.auto.service:auto-service:1.0.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.0.1'
}

tasks.withType(JavaCompile).configureEach {
    source(project(":Common").sourceSets.main.allSource)
}

tasks.withType(Javadoc).configureEach {
    source(project(":Common").sourceSets.main.allJava)
}

tasks.withType(ProcessResources).configureEach {
    from project(":Common").sourceSets.main.resources
}

tasks.named("sourcesJar", Jar) {
    from(project(":Common").sourceSets.main.allSource)
}
